### PR TITLE
Fix DivisionByZeroException in Regen (B)

### LINKED ISSUE #30: Crash in Regen (B) when using Healing Potion.
DivisionByZeroError: "Division by zero" (EXCEPTION) in "plugins/Zuri_dev-9.phar/src/checks/badpackets/regen/RegenB" at line 82
--- Stack trace ---
  #0 plugins/Zuri_dev-9.phar/src/listener/PlayerListener(519): ReinfyTeam\Zuri\checks\badpackets\regen\RegenB->checkEvent(object pocketmine\event\entity\EntityRegainHealthEvent#245403, object ReinfyTeam\Zuri\player\PlayerAPI#46511)
  #1 plugins/Zuri_dev-9.phar/src/listener/PlayerListener(445): ReinfyTeam\Zuri\listener\PlayerListener->checkEvent(object pocketmine\event\entity\EntityRegainHealthEvent#245403, object pocketmine\player\Player#249143)
  #2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onPlayerRegen(object pocketmine\event\entity\EntityRegainHealthEvent#245403)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityRegainHealthEvent#245403)
  #4 pmsrc/src/entity/Entity(549): pocketmine\event\Event->call()
  #5 pmsrc/src/entity/effect/InstantHealthEffect(34): pocketmine\entity\Entity->heal(object pocketmine\event\entity\EntityRegainHealthEvent#245403)
  #6 pmsrc/src/entity/projectile/SplashPotion(124): pocketmine\entity\effect\InstantHealthEffect->applyEffect(object pocketmine\player\Player#249143, object pocketmine\entity\effect\EffectInstance#213109, float 0.87210889604937, object pocketmine\entity\projectile\SplashPotion#359701)
  #7 pmsrc/src/entity/projectile/Projectile(237): pocketmine\entity\projectile\SplashPotion->onHit(object pocketmine\event\entity\ProjectileHitBlockEvent#350720)
  #8 pmsrc/src/entity/Entity(1005): pocketmine\entity\projectile\Projectile->move(float -1.4554866138819, float -0.36905420026223, float 0.19697455205702)
  #9 pmsrc/src/world/World(997): pocketmine\entity\Entity->onUpdate(int 1105933)
  #10 pmsrc/src/world/World(922): pocketmine\world\World->actuallyDoTick(int 1105933)
  #11 pmsrc/src/world/WorldManager(347): pocketmine\world\World->doTick(int 1105933)
  #12 pmsrc/src/Server(1811): pocketmine\world\WorldManager->tick(int 1105933)
  #13 pmsrc/src/Server(1693): pocketmine\Server->tick()
  #14 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[18] /home/admin/Server/, string[26] /home/admin/Server/plugins/)
  #16 pmsrc/src/PocketMine(378): pocketmine\server()
  #17 /home/admin/Server/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPRsq6rN.tar/src/PocketMine.php)
--- End of exception information ---

### PR DESCRIPTION
**Pull request by TrinitroToluen0**

### CODE REVIEW

File: src/checks/badpackets/regen/RegenB.php [hunk 1]
```diff
@@ -84,7 +84,7 @@ public function checkEvent(Event $event, PlayerAPI $playerAPI) : void {
 
 								$this->debug($playerAPI, "healRate=$healRate");
 
-								if ($healRate > 0.5) {
+								if ($healRate > 0.7) {
```
Comment (xRodzMC) [inline src/checks/badpackets/regen/RegenB.php]: Is the heal rate is actually triggers about >0.7?

File: src/checks/badpackets/regen/RegenA.php [hunk 2]
```diff
@@ -64,7 +64,7 @@ public function checkEvent(Event $event, PlayerAPI $playerAPI) : void {
 			if ($event->getRegainReason() != EntityDamageEvent::CAUSE_MAGIC && $event->getRegainReason() != EntityDamageEvent::CAUSE_CUSTOM) {
 				$healAmount = $event->getAmount();
 				$this->debug($playerAPI, "healAmount=$healAmount");
-				if ($healAmount > 3) {
+				if ($healAmount > 3.4) {
```
Comment (xRodzMC) [inline src/checks/badpackets/regen/RegenA.php]: Is this the absolute value when you are using Regen Hack Module? What minecraft hack client you use? It seems to be that it can cause false-positive through potions for ex. health boost...

**Comment by TrinitroToluen0** [comment]
I didn't notice these changes were commited, i just wanted to contribute with the `if($healTime !== 0)`

About the other changes, i didn't tested them, i didn't meant to commit them also, but yeah, Regen (A) and Regen (B) are also triggering without cheats, maybe because my FasterProjectiles plugin, im not sure, but again i didn't want to commit these changes.

**Comment by TrinitroToluen0** [comment]
I commited my personal changes to the same PR branch, that's why 😅, but my contribution was only supposed to be the first commit. I will revert the changes made.

**Review by rodolfoorlandajr — APPROVED** [review]

**Comment by rodolfoorlandajr** [comment]
Thanks for your contribution! Resolves as #30
